[workspace]
members = [
  "noop-str", "noop-string", # to compare size
  "difference-lcs", # abandoned, buggy
  "dissimilar-myers", # large binary size?
  "diffs-myers", # low-level
]

# no artifacts (bins, libs) -> virtual manifest
# -> specify dependencies in workspace members
